### ISSUE TITLE
typo in a2?

### ISSUE THREAD

**Issue by zsat** [umd-cmsc701/s2024#1]
https://github.com/umd-cmsc701/s2024/blob/754cac0184c9d3aa6c924358f40686bc4f134e34/_assignments/bloom_filter.md?plain=1#L40

I presume this line is [copypasted from a1](https://github.com/umd-cmsc701/s2024/blob/gh-pages/_assignments/bitvector_rsa.md?plain=1#L44), just bitvector right?

also, might wanna note if we should floor or ceil the `m` and `k` values when printing in part 1. could check ofc when submitting to gradescope but would be nice to have in the readme :)

**Comment by rob-p** [comment]
Good points; I've updated the spec on the website.
